//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdsSponsored
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAdsSponsored()
        {
            this.tAdsLogs = new HashSet<tAdsLog>();
        }
    
        public int ID { get; set; }
        public int AdTypeID { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public Nullable<int> UserFilterID { get; set; }
        public Nullable<int> IconID { get; set; }
        public string ImagePath { get; set; }
        public string ClickPath { get; set; }
        public int SponsorID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAdsLog> tAdsLogs { get; set; }
        public virtual tAdType tAdType { get; set; }
        public virtual tIcon tIcon { get; set; }
        public virtual tSponsor tSponsor { get; set; }
        public virtual tUserFilter tUserFilter { get; set; }
    }
}
