//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCredential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCredential()
        {
            this.tUserSourceServices = new HashSet<tUserSourceService>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string SourceUserID { get; set; }
        public string AccessToken { get; set; }
        public string PublicToken { get; set; }
        public int SourceID { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public string SourceUserIDToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> AccessTokenExpiration { get; set; }
    
        public virtual tSource tSource { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUserID tUserID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserSourceService> tUserSourceServices { get; set; }
    }
}
