//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProvider()
        {
            this.tProviderPhoneNumbers = new HashSet<tProviderPhoneNumber>();
        }
    
        public int ID { get; set; }
        public string SourceProviderID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string DepartmentName { get; set; }
        public string NPINumber { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual tOrganization tOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProviderPhoneNumber> tProviderPhoneNumbers { get; set; }
    }
}
