//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReligion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tReligion()
        {
            this.tUserReligions = new HashSet<tUserReligion>();
            this.tXrefReligionsCodes = new HashSet<tXrefReligionsCode>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsCommon { get; set; }
        public int SystemStatusID { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserReligion> tUserReligions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefReligionsCode> tXrefReligionsCodes { get; set; }
    }
}
