//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSNPAvailability
    {
        public int ID { get; set; }
        public int SourceServiceID { get; set; }
        public Nullable<long> SourceIndex { get; set; }
        public string SNPProbeName { get; set; }
        public string Chromosome { get; set; }
        public string ChromosomePosition { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
