//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSourceOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSourceOrganization()
        {
            this.tUserSHARESettings = new HashSet<tUserSHARESetting>();
        }
    
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string SourceObjectID { get; set; }
        public int OrganizationID { get; set; }
        public string SourceOrgID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int SourceServiceID { get; set; }
    
        public virtual tOrganization tOrganization { get; set; }
        public virtual tSourceService tSourceService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserSHARESetting> tUserSHARESettings { get; set; }
    }
}
