//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSourceService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSourceService()
        {
            this.tUserSourceService = new HashSet<tUserSourceService>();
        }
    
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public int SourceID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual tSourceServiceType tSourceServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserSourceService> tUserSourceService { get; set; }
    }
}
