//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSurveyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSurveyQuestion()
        {
            this.tSurveyQuestionMCAnswers = new HashSet<tSurveyQuestionMCAnswer>();
        }
    
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public string Question { get; set; }
        public int QuestionTypeID { get; set; }
        public byte IsValid { get; set; }
        public byte CanSkip { get; set; }
    
        public virtual tSurveyQuestionType tSurveyQuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSurveyQuestionMCAnswer> tSurveyQuestionMCAnswers { get; set; }
    }
}
