//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSurvey()
        {
            this.tSurveyQuestions = new HashSet<tSurveyQuestion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public int UserFilterID { get; set; }
        public string InternalName { get; set; }
        public string PublicName { get; set; }
        public string PublicDescription { get; set; }
        public string AvgLengthofTime { get; set; }
        public string MoreInfoLink { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual tSponsor tSponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSurveyQuestion> tSurveyQuestions { get; set; }
        public virtual tUserFilter tUserFilter { get; set; }
    }
}
