//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserPasswordReset
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.Guid ExternalUserID { get; set; }
        public System.Guid ResetCodeID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> UsedDateTime { get; set; }
    
        public virtual tUser tUser { get; set; }
    }
}
