//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserDataAudit
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int EventID { get; set; }
        public string Description { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.Guid> NewObjectID { get; set; }
        public Nullable<System.Guid> OldObjectID { get; set; }
    
        public virtual tUserID tUserID { get; set; }
        public virtual tUserDataAuditType tUserDataAuditType { get; set; }
    }
}
