//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserDataAuditType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUserDataAuditType()
        {
            this.tUserDataAudits = new HashSet<tUserDataAudit>();
        }
    
        public int ID { get; set; }
        public string InternalName { get; set; }
        public string DisplayDescription { get; set; }
        public bool IsDisplayed { get; set; }
        public int SystemStatusID { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserDataAudit> tUserDataAudits { get; set; }
    }
}
