//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserNarrativeEntry
    {
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public int NarrativeID { get; set; }
        public int SectionSeqNum { get; set; }
        public string SectionTitle { get; set; }
        public string SectionText { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public int SystemStatusID { get; set; }
    
        public virtual tUserNarrative tUserNarrative { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
    }
}
