//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserTestResultComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUserTestResultComponent()
        {
            this.tXrefUserTestResultComponentsCodes = new HashSet<tXrefUserTestResultComponentsCode>();
        }
    
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public int TestResultID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> UOMID { get; set; }
        public string LowValue { get; set; }
        public string HighValue { get; set; }
        public string RefRange { get; set; }
        public string Comments { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure { get; set; }
        public virtual tUserTestResult tUserTestResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserTestResultComponentsCode> tXrefUserTestResultComponentsCodes { get; set; }
    }
}
