//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUser()
        {
            this.tUsersAddressHistories = new HashSet<tUsersAddressHistory>();
            this.tUsersAudits = new HashSet<tUsersAudit>();
            this.tUsersErrLogs = new HashSet<tUsersErrLog>();
            this.tXrefUsersMaritalStatus = new HashSet<tXrefUsersMaritalStatu>();
            this.tUserLoginAuths = new HashSet<tUserLoginAuth>();
            this.tUserPasswordResets = new HashSet<tUserPasswordReset>();
        }
    
        public int ID { get; set; }
        public System.Guid ExternalID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> PHSaltID { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<int> AccountStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tAccountStatu tAccountStatu { get; set; }
        public virtual tEthnicity tEthnicity { get; set; }
        public virtual tGender tGender { get; set; }
        public virtual tLanguage tLanguage { get; set; }
        public virtual tRace tRace { get; set; }
        public virtual tSalt tSalt { get; set; }
        public virtual tSex tSex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUsersAddressHistory> tUsersAddressHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUsersAudit> tUsersAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUsersErrLog> tUsersErrLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUsersMaritalStatu> tXrefUsersMaritalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserLoginAuth> tUserLoginAuths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserPasswordReset> tUserPasswordResets { get; set; }
    }
}
