//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserTestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUserTestResult()
        {
            this.tUserTestResultComponents = new HashSet<tUserTestResultComponent>();
            this.tXrefUserTestResultRecipientsProviders = new HashSet<tXrefUserTestResultRecipientsProvider>();
            this.tXrefUserTestResultsCodes = new HashSet<tXrefUserTestResultsCode>();
        }
    
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string SourceObjectID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SourceOrganizationID { get; set; }
        public Nullable<int> UserSourceServiceID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderingProviderID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comments { get; set; }
        public string Narrative { get; set; }
        public string Impression { get; set; }
        public string Transcriptions { get; set; }
        public System.DateTimeOffset ResultDateTime { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tProvider tProvider { get; set; }
        public virtual tSourceOrganization tSourceOrganization { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tTestResultStatus tTestResultStatus { get; set; }
        public virtual tUserID tUserID { get; set; }
        public virtual tUserSourceService tUserSourceService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserTestResultComponent> tUserTestResultComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserTestResultRecipientsProvider> tXrefUserTestResultRecipientsProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserTestResultsCode> tXrefUserTestResultsCodes { get; set; }
    }
}
