//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserSNPProbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUserSNPProbe()
        {
            this.tXrefUserSNPProbesSNPAvailabilities = new HashSet<tXrefUserSNPProbesSNPAvailability>();
        }
    
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public Nullable<int> SourceObjectID { get; set; }
        public int UserID { get; set; }
        public int SourceOrganizationID { get; set; }
        public Nullable<int> UserSourceServiceID { get; set; }
        public string GenotypeCall { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUserID tUserID { get; set; }
        public virtual tUserSourceService tUserSourceService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserSNPProbesSNPAvailability> tXrefUserSNPProbesSNPAvailabilities { get; set; }
    }
}
