//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserImmunizationsDate
    {
        public int ID { get; set; }
        public int UserImmunizationID { get; set; }
        public System.DateTimeOffset DateTime { get; set; }
        public int SystemStatusID { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
    }
}
