//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserPrescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUserPrescription()
        {
            this.tXrefUserEncountersPrescriptions = new HashSet<tXrefUserEncountersPrescription>();
            this.tXrefUserPrescriptionsCodes = new HashSet<tXrefUserPrescriptionsCode>();
        }
    
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string SourceObjectID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SourceOrganizationID { get; set; }
        public Nullable<int> UserSourceServiceID { get; set; }
        public string Name { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string DosageText { get; set; }
        public string DosageValue { get; set; }
        public Nullable<int> MedFormID { get; set; }
        public string FrequencyValue { get; set; }
        public Nullable<int> FrequencyUOMID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string StrengthValue { get; set; }
        public Nullable<int> StrengthUOMID { get; set; }
        public Nullable<int> PharmacyID { get; set; }
        public Nullable<int> RefillsRemaining { get; set; }
        public Nullable<int> RefillsTotal { get; set; }
        public Nullable<System.DateTimeOffset> ExpirationDateTime { get; set; }
        public System.DateTimeOffset StartDateTime { get; set; }
        public Nullable<System.DateTimeOffset> EndDateTime { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tMedicationForm tMedicationForm { get; set; }
        public virtual tMedicationRoute tMedicationRoute { get; set; }
        public virtual tPharmacy tPharmacy { get; set; }
        public virtual tProvider tProvider { get; set; }
        public virtual tSourceOrganization tSourceOrganization { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure1 { get; set; }
        public virtual tUserID tUserID { get; set; }
        public virtual tUserSourceService tUserSourceService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserEncountersPrescription> tXrefUserEncountersPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tXrefUserPrescriptionsCode> tXrefUserPrescriptionsCodes { get; set; }
    }
}
