//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserActivity
    {
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string SourceObjectID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> UserSourceServiceID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> DurationUOMID { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> DistanceUOMID { get; set; }
        public Nullable<decimal> Steps { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> LightActivityMin { get; set; }
        public Nullable<decimal> ModerateActivityMin { get; set; }
        public Nullable<decimal> VigorousActivityMin { get; set; }
        public Nullable<decimal> SedentaryActivityMin { get; set; }
        public System.DateTimeOffset StartDateTime { get; set; }
        public Nullable<System.DateTimeOffset> EndDateTime { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tActivity tActivity { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure1 { get; set; }
        public virtual tUserID tUserID { get; set; }
        public virtual tUserSourceService tUserSourceService { get; set; }
    }
}
