//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserEncounterReason
    {
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string Value { get; set; }
        public int UserEncounterID { get; set; }
        public int SystemStatusID { get; set; }
    
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUserEncounter tUserEncounter { get; set; }
    }
}
