//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserOrder
    {
        public int ID { get; set; }
        public System.Guid ObjectID { get; set; }
        public int EncounterID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTimeOffset> ExpectedDate { get; set; }
        public Nullable<System.DateTimeOffset> ExpirationDate { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> CodeID { get; set; }
        public int SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual tCode tCode { get; set; }
        public virtual tOrderType tOrderType { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
        public virtual tUserEncounter tUserEncounter { get; set; }
    }
}
