//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tXrefUserSNPProbesSNPAvailability
    {
        public int ID { get; set; }
        public int SNPAvailabilityID { get; set; }
        public int UserSNPProbeID { get; set; }
    
        public virtual tSNPAvailability tSNPAvailability { get; set; }
        public virtual tUserSNPProbe tUserSNPProbe { get; set; }
    }
}
