//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tXrefUserSHARESettingsPurpos
    {
        public int ID { get; set; }
        public int SHAREPurposeID { get; set; }
        public int SHARESettingID { get; set; }
    
        public virtual tSHAREPurpose tSHAREPurpos { get; set; }
        public virtual tUserSHARESetting tUserSHARESetting { get; set; }
    }
}
