//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tXrefUserDietNutrient
    {
        public int ID { get; set; }
        public int UserDietID { get; set; }
        public int NutrientID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> SystemStatusID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual tNutrient tNutrient { get; set; }
        public virtual tUnitsOfMeasure tUnitsOfMeasure { get; set; }
        public virtual tUserDiet tUserDiet { get; set; }
        public virtual tSystemStatus tSystemStatus { get; set; }
    }
}
