//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Users
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersEntities : DbContext
    {
        public UsersEntities()
            : base("name=UsersEntities")
        {
    		base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAccountStatu> tAccountStatus { get; set; }
        public virtual DbSet<tCountry> tCountries { get; set; }
        public virtual DbSet<tEthnicity> tEthnicities { get; set; }
        public virtual DbSet<tGender> tGenders { get; set; }
        public virtual DbSet<tLanguage> tLanguages { get; set; }
        public virtual DbSet<tMaritalStatus> tMaritalStatuses { get; set; }
        public virtual DbSet<tRace> traces { get; set; }
        public virtual DbSet<tSalt> tSalts { get; set; }
        public virtual DbSet<tSex> tSexes { get; set; }
        public virtual DbSet<tState> tStates { get; set; }
        public virtual DbSet<tTimeZone> tTimeZones { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tUsersAddressHistory> tUsersAddressHistories { get; set; }
        public virtual DbSet<tUsersAudit> tUsersAudits { get; set; }
        public virtual DbSet<tUsersErrLog> tUsersErrLogs { get; set; }
        public virtual DbSet<tXrefUsersMaritalStatu> tXrefUsersMaritalStatus { get; set; }
        public virtual DbSet<tUserLoginAuth> tUserLoginAuths { get; set; }
        public virtual DbSet<tUsersAuditType> tUsersAuditTypes { get; set; }
        public virtual DbSet<tUserPasswordReset> tUserPasswordResets { get; set; }
        public virtual DbSet<tSystemStatus> tSystemStatuses { get; set; }
    }
}
