//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.WebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApplicationEntities : DbContext
    {
        public WebApplicationEntities()
            : base("name=WebApplicationEntities")
        {
    		base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAdsLog> tAdsLogs { get; set; }
        public virtual DbSet<tAdsSponsored> tAdsSponsoreds { get; set; }
        public virtual DbSet<tAdType> tAdTypes { get; set; }
        public virtual DbSet<tIcon> tIcons { get; set; }
        public virtual DbSet<tInvitationCode> tInvitationCodes { get; set; }
        public virtual DbSet<tSponsor> tSponsors { get; set; }
        public virtual DbSet<tSurveyQuestion> tSurveyQuestions { get; set; }
        public virtual DbSet<tSurveyQuestionType> tSurveyQuestionTypes { get; set; }
        public virtual DbSet<tSurvey> tSurveys { get; set; }
        public virtual DbSet<tUserFilter> tUserFilters { get; set; }
        public virtual DbSet<tUserID> tUserIDs { get; set; }
        public virtual DbSet<tWAAudit> tWAAudits { get; set; }
        public virtual DbSet<tWAAuditObject> tWAAuditObjects { get; set; }
        public virtual DbSet<tWAErrLog> tWAErrLogs { get; set; }
        public virtual DbSet<tSurveyQuestionMCAnswer> tSurveyQuestionMCAnswers { get; set; }
    }
}
